app/routes/empresa.py
from flask import Blueprint, render_template, redirect, url_for, session, abort, current_app, request
from werkzeug.utils import secure_filename

from app.forms import FormCadastro_Emp, FormLogin_Emp, FormProduto
from app.models import Empresa, Product, Order
from app.extensions import bcrypt, db
from app.decorators import empresa_login_required
from flask_login import login_required

import os


empresa_bp = Blueprint("empresa", __name__, url_prefix="/empresa")

@empresa_bp.route("/empresa/cadastro", methods=["GET","POST"])
def cadastro_empresa():
    form = FormCadastro_Emp()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.senha.data)
        emp = Empresa(
            username=form.username.data,
            senha=hashed,
            email=form.email.data
            )
        db.session.add(emp)
        db.session.commit()

        session["empresa_id"] = emp.id
        return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("empresa/e_cadastro.html", form=form)

@empresa_bp.route("/empresa/login", methods=["GET", "POST"])
def login_empresa():
    form = FormLogin_Emp()

    if form.validate_on_submit():
        emp = Empresa.query.filter_by(email=form.email.data).first()
        if emp and bcrypt.check_password_hash(emp.senha, form.senha.data):
            session["empresa_id"] = emp.id
            return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("empresa/e_login.html", form=form)


@empresa_bp.route("/add_produtos/<int:id_empresa>", methods=["GET", "POST"])
@empresa_login_required
def add_produtos(id_empresa):
    emp = Empresa.query.get_or_404(id_empresa)
    form = FormProduto()
    
    if session.get("empresa_id") == emp.id and form.validate_on_submit():
        imagem = form.imagem.data
        filename = secure_filename(imagem.filename)
        imagem.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

        novo = Product(
            name=form.nome.data,
            descricao = form.descricao.data,
            price=form.preco.data,
            imagem=filename,  # somente nome ou caminho
            empresa_id=emp.id
        )
        db.session.add(novo)
        db.session.commit()
        return redirect(url_for("empresa.add_produtos", id_empresa=emp.id))

    return render_template(
        "empresa/e_produtos.html", empresa=emp, produtos=emp.produtos, form=form if session.get("empresa_id") == emp.id else None)

@empresa_bp.route("/e_perfil/<int:id_empresa>")
@empresa_login_required
def e_perfil(id_empresa):
    empresa = Empresa.query.get_or_404(id_empresa)

    # Só permite se a empresa logada for a dona do perfil
    if session.get("empresa_id") != empresa.id:
        abort(403)

    ordens = Order.query.filter_by(empresa_id=empresa.id).all()

    return render_template("empresa/e_perfil.html", empresa=empresa, ordens=ordens)

@empresa_bp.route("/empresa/logout")
def logout_empresa():
    session.pop("empresa_id", None)
    return redirect(url_for("geral.homepage"))

@empresa_bp.route('/toggle_status/<int:empresa_id>', methods=['POST'])
@empresa_login_required
def toggle_status(empresa_id):
    empresa = Empresa.query.get_or_404(empresa_id)
    empresa.aberto = not empresa.aberto
    db.session.commit()
    return redirect(request.referrer or url_for('empresa.e_perfil', empresa_id=empresa_id))

app/routes/geral.py
from flask import Blueprint, render_template, redirect, url_for
from flask import render_template, url_for, redirect, session
from flask_login import login_required, current_user
from app.models import Empresa
#from templates.

geral_bp = Blueprint("geral", __name__)

@geral_bp.route("/")
def homepage():
    if current_user.is_authenticated:
        return redirect(url_for("usuario.perfil"))
    elif "empresa_id" in session:
        emp = Empresa.query.get(session["empresa_id"])
        if emp:
            return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("geral/homepage.html")


@geral_bp.route("/pesquisa")
def pesquisa():
    return render_template("geral/pesquisa.html")

@geral_bp.route("/sobre")
def sobre():
    return render_template("geral/sobre.html")

app/templates/empresa/e_cadastro.html
{% extends "geral/others_lay.html" %}
{% block title %}
RondoFood - Cadastro
{% endblock %}
{% block content %}
    <h2> Faça seu cadastro</h2>

    <form method="POST">
        {{ form.csrf_token }}

        {{form.username.label()}}
        {{form.username()}}
       
        {{form.email.label()}}
        {{form.email()}}
        
        {{form.senha.label()}}
        {{form.senha()}}

        {{form.confirmacao_senha.label()}}
        {{form.confirmacao_senha()}}

        
        {{form.botao_confirmacao}}
{% endblock %}

app/templates/empresa/e_layout.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %} RonDelivery {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css')}}" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='fotos_app/' ~ ('ronic.png')) }}" type="image/x-icon">
    </head>

    <body>
        <div class="navbar">
            <a href="{{ url_for('empresa.e_perfil', id_empresa=empresa_logada.id) }}" class="navbar-item">Perfil da Empresa</a>
            <a href="{{ url_for('empresa.add_produtos', id_empresa=empresa_logada.id) }}" class="navbar-item">Cardápio</a>
            <!-- <a href="{{ url_for('geral.sobre') }}" class="navbar-item">Sobre Nós</a> -->
            <a href="{{ url_for('empresa.logout_empresa') }}" class="navbar-item">Sair</a>
        </div>

        <div class="body-content">
            {% block content %}
            {% endblock %}
           
            <footer>
                <p>&copy; Faccin Engenharia e Tecnologia 2025</p>
            </footer>
        </div>
    </body>
</html>

app/templates/empresa/e_login.html
{% extends "geral/others_lay.html" %}
{% block title %}
RondoFood - Login
{% endblock %}
{% block content %}
    <h1> Faça seu login</h1>
    <h2> Acesso apenas para empresas!</h2>

<form method="POST">
     {{ form.csrf_token }}
        {{form.email.label()}}
        {{form.email()}}
        
        {{form.senha.label()}}
        {{form.senha()}}

        {{form.botao_confirmacao}}


</form>
{% endblock %}

app/templates/empresa/e_perfil.html
{% extends "empresa/e_layout.html" %}
{% block title %}
{{ empresa_logada.username }} - Perfil
{% endblock %}
{% block content %}
<h2>  Ordens </h2>
  <p>Olá, {{ empresa_logada.username }}</p>

  <form action="{{ url_for('empresa.toggle_status', empresa_id=empresa.id)}}" method="post">
    <button type="submit">
        {{'Aberto' if empresa.aberto else 'Fechado'}}
    </button>
  </form>

<ul>
    {% for order in orders %}
        <li>Pedido #{{ order.id }} em {{ order.criacao }}</li>
    {% else %}
        <li> Nenhum pedido encontrado.</li>
    {% endfor %}
</ul>

<a href="{{ url_for('empresa.logout_empresa')}}"> Sair </a>
{% endblock %}

app/templates/empresa/e_produtos.html
{% extends "empresa/e_layout.html" %}
{% block title %}
Rondofood - Produtos
{% endblock %}
{% block content %}
<h2>{{ empresa_logada.username }} - Produtos </h2>




{% if form %}
<h3> Adicionar novo produto</h3>
<form method="POST" enctype="multipart/form-data">
    {{form.csrf_token}}
    {{form.nome.label}} {{form.nome() }} <br>
    {{form.descricao.label}} {{form.descricao() }} <br>
    {{ form.preco.label }} {{ form.preco() }}<br>
    {{ form.imagem.label }} {{ form.imagem() }}<br>
    {{ form.botao_confirmacao }}
</form>
{% endif %}

<ul>
    {% for produto  in produtos %}
    <li>
    <img src="{{ url_for('static', filename='fotos_prod/{}'. format(produto.imagem))}}" width="200" alt="{{ produto.name }}">
    <strong>{{ produto.name }}</strong> – R$ {{ "%.2f"|format(produto.price) }}
    </li>
    {% endfor %}
</ul>

{% endblock %}


<!-- adicionar opção para editar itens -->