app/routes/empresa.py
from flask import Blueprint, render_template, redirect, url_for, session, abort, current_app, request
from werkzeug.utils import secure_filename

from app.forms import FormCadastro_Emp, FormLogin_Emp, FormProduto
from app.models import Empresa, Product, Order
from app.extensions import bcrypt, db
from app.decorators import empresa_login_required
from flask_login import login_required

import os


empresa_bp = Blueprint("empresa", __name__, url_prefix="/empresa")

@empresa_bp.route("/empresa/cadastro", methods=["GET","POST"])
def cadastro_empresa():
    form = FormCadastro_Emp()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.senha.data)
        emp = Empresa(
            username=form.username.data,
            senha=hashed,
            email=form.email.data
            )
        db.session.add(emp)
        db.session.commit()

        session["empresa_id"] = emp.id
        return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("empresa/e_cadastro.html", form=form)

@empresa_bp.route("/empresa/login", methods=["GET", "POST"])
def login_empresa():
    form = FormLogin_Emp()

    if form.validate_on_submit():
        emp = Empresa.query.filter_by(email=form.email.data).first()
        if emp and bcrypt.check_password_hash(emp.senha, form.senha.data):
            session["empresa_id"] = emp.id
            return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("empresa/e_login.html", form=form)


@empresa_bp.route("/add_produtos/<int:id_empresa>", methods=["GET", "POST"])
@empresa_login_required
def add_produtos(id_empresa):
    emp = Empresa.query.get_or_404(id_empresa)
    form = FormProduto()
    
    if session.get("empresa_id") == emp.id and form.validate_on_submit():
        imagem = form.imagem.data
        filename = secure_filename(imagem.filename)
        imagem.save(os.path.join(current_app.config['UPLOAD_FOLDER'], filename))

        novo = Product(
            name=form.nome.data,
            descricao = form.descricao.data,
            price=form.preco.data,
            imagem=filename,  # somente nome ou caminho
            empresa_id=emp.id
        )
        db.session.add(novo)
        db.session.commit()
        return redirect(url_for("empresa.add_produtos", id_empresa=emp.id))

    return render_template(
        "empresa/e_produtos.html", empresa=emp, produtos=emp.produtos, form=form if session.get("empresa_id") == emp.id else None)

@empresa_bp.route("/e_perfil/<int:id_empresa>")
@empresa_login_required
def e_perfil(id_empresa):
    empresa = Empresa.query.get_or_404(id_empresa)

    # Só permite se a empresa logada for a dona do perfil
    if session.get("empresa_id") != empresa.id:
        abort(403)

    ordens = Order.query.filter_by(empresa_id=empresa.id).all()

    return render_template("empresa/e_perfil.html", empresa=empresa, ordens=ordens)

@empresa_bp.route("/empresa/logout")
def logout_empresa():
    session.pop("empresa_id", None)
    return redirect(url_for("geral.homepage"))

@empresa_bp.route('/toggle_status/<int:empresa_id>', methods=['POST'])
@empresa_login_required
def toggle_status(empresa_id):
    empresa = Empresa.query.get_or_404(empresa_id)
    empresa.aberto = not empresa.aberto
    db.session.commit()
    return redirect(request.referrer or url_for('empresa.e_perfil', empresa_id=empresa_id))

app/routes/geral.py
from flask import Blueprint, render_template, redirect, url_for
from flask import render_template, url_for, redirect, session
from flask_login import login_required, current_user
from app.models import Empresa
#from templates.

geral_bp = Blueprint("geral", __name__)

@geral_bp.route("/")
def homepage():
    if current_user.is_authenticated:
        return redirect(url_for("usuario.perfil"))
    elif "empresa_id" in session:
        emp = Empresa.query.get(session["empresa_id"])
        if emp:
            return redirect(url_for("empresa.e_perfil", id_empresa=emp.id))
    return render_template("geral/homepage.html")


@geral_bp.route("/pesquisa")
def pesquisa():
    return render_template("geral/pesquisa.html")

@geral_bp.route("/sobre")
def sobre():
    return render_template("geral/sobre.html")

app/routes/usuario.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required, logout_user, login_user

from app.forms import FormLogin, FormCadastro, EnderecoForm
from app.models import Empresa, Usuario, Product, Endereco
from app.extensions import bcrypt, db

usuario_bp = Blueprint("usuario", __name__, url_prefix="/usuario")

@usuario_bp.route("/login", methods=["GET","POST"])
def login():
    formlogin = FormLogin()
    if formlogin.validate_on_submit():
        usuario= Usuario.query.filter_by(email=formlogin.email.data).first()
        if usuario and bcrypt.check_password_hash(usuario.senha, formlogin.senha.data):
            login_user(usuario)
            return redirect(url_for("usuario.perfil", usuario=current_user))
    return render_template("usuario/login.html", form=formlogin)

@usuario_bp.route("/cadastro", methods=["GET","POST"])
def cadastro():
    formcadastro = FormCadastro()
    if formcadastro.validate_on_submit():
        senha = bcrypt.generate_password_hash(formcadastro.senha.data)
        usuario = Usuario(username=formcadastro.username.data, senha=senha, email=formcadastro.email.data)

        db.session.add(usuario)
        db.session.commit()
        login_user(usuario, remember=True)
        # db.session.refresh(usuario)
        return redirect(url_for("usuario.perfil", usuario=current_user))
    return render_template("usuario/cadastro.html", form=formcadastro)

@usuario_bp.route("/perfil")
@login_required
def perfil():
    return render_template("usuario/perfil.html", user=current_user) 

@usuario_bp.route("/perfil/enderecos", methods=["GET","POST"])
@login_required
def gerenciar_enderecos():
    form = EnderecoForm()
    if form.validate_on_submit():
        novo_end = Endereco(
            usuario_id=current_user.id,
            tipo_end=form.tipo_end.data,
            endereco=form.endereco.data,
            numero=form.numero.data,
            bairro=form.bairro.data,
            complemento=form.complemento.data,
        )
        db.session.add(novo_end)
        db.session.commit()
        return redirect(url_for("usuario.gerenciar_enderecos"))
    enderecos = Endereco.query.filter_by(usuario_id=current_user.id).all()
    return render_template(
        "usuario/enderecos.html",
        form=form,
        enderecos=enderecos,
        user=current_user)


@usuario_bp.route("/produtos/<int:id_empresa>", methods=["GET", "POST"])
def produtos(id_empresa):
    empresa = Empresa.query.get_or_404(id_empresa)
    produtos = empresa.produtos
    return render_template("usuario/produtos.html", empresa=empresa, produtos=empresa.produtos)

@usuario_bp.route("/inicio")
def inicio():
    empresas = Empresa.query.filter_by(aberto=True).all()
    return render_template("usuario/inicio.html", empresas=empresas)

@usuario_bp.route("/carrinho") #, methods=['POST']
@login_required
def carrinho():
    return render_template("usuario/carrinho.html")

@usuario_bp.route("/logout")
@login_required
def logout():
    logout_user() #ele já sabe que precisa deslogar o current user
    return render_template("usuario/logout.html")

app/templates/geral/homepage.html
{% extends "geral/others_lay.html" %}
{% block title %}
RonDelivery - Inicio
{% endblock %}
{% block content %}


<h2> Usuário </h2>
<a href="{{ url_for('usuario.login')}}"> Entrar </a>
<a href="{{ url_for('usuario.cadastro')}}"> Cadastro </a>

<h2> Empresa </h2>
<a href="{{ url_for('empresa.login_empresa')}}"> Entrar </a>
<a href="{{ url_for('empresa.cadastro_empresa')}}"> Cadastro </a>

    <img src="{{ url_for('static', filename='fotos_app/' ~ ('ronico.png')) }}" alt="logo RonDelivery" width="700">

<a href="{{ url_for('usuario.inicio')}}"> Entrar como Visitante </a>
{% endblock %}

app/templates/geral/others_lay.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %} RonDelivery {% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css')}}" />
        <link rel="shortcut icon" href="{{ url_for('static', filename='fotos_app/' ~ ('ronic.png')) }}" type="image/x-icon">
    </head>

    <body>
        <div class="navbar">
            <a href="{{ url_for('geral.homepage') }}">Home</a>
            <a href="{{ url_for('geral.sobre') }}" class="navbar-item">Sobre Nós</a>
        </div>
        
            <div class="body-content">
            {% block content %}
            {% endblock %}
            
            <footer>
                <p>&copy; Faccin Engenharia e Tecnologia 2025</p>
            </footer>
        </div>
    </body>
</html>

app/templates/geral/pesquisa.html
{% extends "layout.html" %}
{% block title %}
RonDelivery - Pesquisar
{% endblock %}
{% block content %}


{% endblock %}

app/templates/geral/sobre.html
{% extends "geral/others_lay.html" %}
{% block title %}
RonDelivery
{% endblock %}
{% block content %}

<h1>RonDelivery: A Jornada de Um Aplicativo Feito em Rondônia Para Rondônia</h1>
<p>Em um mundo dominado por gigantes corporativos do delivery, onde os algoritmos priorizam lucro sobre pessoas e as taxas sufocam pequenos negócios, surgiu uma alternativa genuinamente rondoniense: o RonDelivery. Nascido no coração do estado, mais precisamente no município de Espigão d'Oeste, esse aplicativo foi desenvolvido de forma independente, com um propósito claro: <strong>valorizar o comércio local e oferecer uma opção justa para entregadores, restaurantes e clientes.</strong></p>

<h2>A Origem: Um pequeno na terra de gigantes</h2>
<p>Enquanto aplicativos internacionais expandiam seus domínios, cobrando taxas abusivas e ditando regras que muitas vezes prejudicavam entregadores e estabelecimentos, um desenvolvedor decidiu agir. Sozinho, mergulhou no desafio de criar uma plataforma que fizesse menção a Rondônia (Ron-Delivery), carregando em seu nome a identidade do estado.

Espigão d'Oeste, uma cidade conhecida por sua força e resistência, foi o berço desse projeto. Ali, entre desafios técnicos e a falta de recursos de grandes empresas, o RonDelivery começou a tomar forma—não como mais um app no mercado, mas como uma ferramenta de resistência econômica e cultural.</p>

<h2>Feito por Rondonienses, Para Rondonienses</h2>
<p>O RonDelivery não é apenas mais um aplicativo de entrega. Ele foi pensado para:

✔ Reduzir taxas para comerciantes, permitindo que mais lucro fique nas mãos de quem produz.
✔ Valorizar entregadores locais, com condições mais justas de trabalho.
✔ Promover estabelecimentos de Rondônia, fortalecendo a economia regional.
✔ Ter um toque rondoniense, desde o nome até a experiência do usuário.

Enquanto as multinacionais padronizam seus serviços para todo o Brasil, o RonDelivery busca entender as particularidades do estado, criando um vínculo real com sua gente.</p>

<h2>O Futuro: Resistir, Crescer e Fortalecer</h2>
<p>Ainda que a jornada seja desafiadora, o RonDelivery prova que é possível competir com as grandes corporações quando se tem um propósito verdadeiro. Seu crescimento depende do apoio de quem acredita que Rondônia merece soluções feitas por rondonienses, para rondonienses.

E você? Vai continuar alimentando impérios corporativos ou vai aderir a um movimento que valoriza o que é nosso?

RonDelivery: Delivery com orgulho de Rondônia! 🚀💛

(Desenvolvido em Espigão d'Oeste, feito para todo o estado!)</p>


{% endblock %}